/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    Filter: typeof import('./components/Base/Filter.vue')['default']
    IconLoader: typeof import('./components/IconLoader.vue')['default']
    Input: typeof import('./components/Base/Input.vue')['default']
    Modal: typeof import('./components/Base/Modal.vue')['default']
    ProductDetails: typeof import('./components/ProductDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Base/Table.vue')['default']
    Tabs: typeof import('./components/Base/Tabs.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
